_commit: v1.2.4-1-gce817c2
_src_path: .
add_compile_target: true
add_executable_target: true
add_header_only_target: true
add_jni_target: true
author_email: msclock@126.com
author_name: msclock
copyright_holder: msclock
copyright_license: MIT License
copyright_year: 2022-2023
create_devcontainer: true
docs_type: sphinx
organization_name: msclock
project_description: A development-focused Cpp project template.
project_name: Cpp Scaffold
repo_host_type: github.com
repo_name: cpp-scaffold
repo_namespace: msclock
use_cdash: false
use_conan: false
use_cpm: false
