_commit: 576eba9
_src_path: .
author_email: msclock@cpp-scaffold.com
author_name: msclock
copyright_holder: cpp scaffold
copyright_license: MIT License
copyright_year: 2022-2023
organization_name: cpp scaffold
project_description: A development-focused Cpp project template.
project_name: Cpp Scaffold
repo_host_type: github.com
repo_name: cpp-scaffold
repo_namespace: cpp-scaffold
