# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  apt_packages:
    - doxygen
    - gcc
    - g++
    - git
    - bash
    - lcov
  jobs:
    post_create_environment:
      - >-
        git clone
        -c core.eol=lf
        -c core.autocrlf=false
        -c safe.directory="/tmp/vcpkg"
        -c fsck.zeroPaddedFilemode=ignore
        -c fetch.fsck.zeroPaddedFilemode=ignore
        -c receive.fsck.zeroPaddedFilemode=ignore https://github.com/microsoft/vcpkg /tmp/vcpkg
      - /tmp/vcpkg/bootstrap-vcpkg.sh
      - /tmp/vcpkg/vcpkg --version
      - pip install cmake ninja
    pre_build:
      - VCPKG_ROOT=/tmp/vcpkg cmake -S . --preset=x64-Debug-GNUC
      - cmake --build out/build/x64-Debug-GNUC --parallel 8 --target ccov-all
    post_build:
      - rm -rf $READTHEDOCS_OUTPUT/html/*
      - cp -r out/build/x64-Debug-GNUC/cpp-scaffold_docs/* $READTHEDOCS_OUTPUT/html/

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: docs/requirements.txt
