# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
    apt_packages:
      - doxygen
      - gcc
      - g++
  commands:
    - |
      git clone --depth 1 https://github.com/msclock/features.git /tmp/vcpkg

      USERNAME="$USER" VCPKGVERSION="latest" VCPKGROOT="/usr/local/vcpkg" \
        VCPKGDOWNLOAD="/usr/local/vcpkg-downloads" /tmp/vcpkg/src/vcpkg/install.sh
      vcpkg --version

      cmake -S . --preset=x64-Debug-GNUC
      cmake --build out/build/x64-Debug-GNUC --parallel 8 --target ccov-all
      cp out/build/x64-Debug-GNUC/cpp-scaffold_docs public/ -r


# Build documentation in the docs/ directory with Sphinx
sphinx:
  # Fail on all warnings to avoid broken references
  fail_on_warning: true

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: docs/requirements.txt
