name: Auto approve

on: pull_request_target

jobs:
  approve:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: Auto approved automated PR
