name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - master

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Avoid checking out the repository in a detached state.
          ref: ${{ github.head_ref }}

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Run pre-commit on codebase
        uses: pre-commit/action@v3.0.0

      - name: Auto commit action
        uses: stefanzweifel/git-auto-commit-action@v4
        if: failure()
        with:
          commit_message: 'ci: auto fixes from pre-commit'

  consistency:
    if: ${{ !cancelled() && ! failure() }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install copier for template rendering using pipx
        run: pipx install copier

      - name: Generate the project with the default value
        run: |
          find . -maxdepth 1 ! -name '.' \
            ! -name 'template' \
            ! -name 'includes' \
            ! -name '.git' \
            ! -name 'copier.yml' \
            ! -name 'CHANGELOG.md' \
            -exec rm -r {} +
          copier copy -r HEAD -f . .
          rm .copier-answers.yml

      - name: Test for consistency
        run: |
          echo "List inconsistent files:"
          git status --porcelain
          git diff --exit-code || ( \
            echo "# :warning: Inconsistent files found" >> $GITHUB_STEP_SUMMARY && \
            echo "The following files are inconsistent with the template:" >> $GITHUB_STEP_SUMMARY && \
            git status --porcelain | while read file; do echo "- $file"; done >> $GITHUB_STEP_SUMMARY && \
            echo "" >> $GITHUB_STEP_SUMMARY && \
            echo "Please run 'copier copy -r HEAD -f . .' to fix them." >>$GITHUB_STEP_SUMMARY && \
            exit 1 \
          )

  pass:
    if: always()
    needs: [pre-commit, consistency]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [pass]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          semantic_version: 22.0.5
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'master',
              'main',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/github
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
